Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,8 +1,5 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Update Language Source
 
-# Controls when the action will run. 
 on:
   schedule:
     - cron:  '*/5 * * * *'
@@ -17,8 +14,8 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Update Projects Source Json
-        run: wget https://demo.foundryvtt.com/lang/en.json -O ./.github/en.json
-        
+        run: wget https://demo.foundryvtt.com/lang/en.json -O ./.github/en.json || echo "Failed in updating language file from Foundry VTT official demo site"
+
       - name: Add & Commit
         uses: EndBug/add-and-commit@v7.2.1
         with:
